---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-oran-o2-tox-py39
        - k8sapp-oran-o2-tox-pylint
        - k8sapp-oran-o2-tox-flake8
        - k8sapp-oran-o2-tox-metadata
        - k8sapp-oran-o2-tox-coverage:
            voting: false
        - k8sapp-oran-o2-tox-bandit:
            voting: false
        - k8sapp-oran-o2-tox-py313:
            voting: false
        - k8sapp-oran-o2-tox-pylint-trixie:
            voting: false
        - k8sapp-oran-o2-tox-flake8-trixie:
            voting: false
        - k8sapp-oran-o2-tox-metadata-trixie:
            voting: false
        - k8sapp-oran-o2-tox-coverage-trixie:
            voting: false
        - k8sapp-oran-o2-tox-bandit-trixie:
            voting: false
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-oran-o2-tox-py39
        - k8sapp-oran-o2-tox-pylint
        - k8sapp-oran-o2-tox-flake8
        - k8sapp-oran-o2-tox-metadata
    post:
      jobs:
        - stx-app-oran-o2-upload-git-mirror

- job:
    name: k8sapp-oran-o2-tox-py39
    parent: tox-py39
    description: |
      Run py39 test for k8sapp-oran-o2
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: py39
      python_version: 3.9
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp-oran-o2
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp-oran-o2
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp-oran-o2
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-coverage
    parent: tox
    description: |
      Run coverage analysis for k8sapp-oran-o2
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: coverage
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'
    post-run: python3-k8sapp-oran-o2/k8sapp_oran_o2/k8sapp_oran_o2/tests/playbooks/upload-coverage-reports.yaml

- job:
    name: k8sapp-oran-o2-tox-bandit
    parent: tox
    description: |
      Run bandit security analysis for k8sapp-oran-o2
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'
    post-run: python3-k8sapp-oran-o2/k8sapp_oran_o2/k8sapp_oran_o2/tests/playbooks/upload-bandit-reports.yaml

- job:
    name: stx-app-oran-o2-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/app-oran-o2 to
      github.com/starlingx/app-oran-o2
    vars:
      git_mirror_repository: starlingx/app-oran-o2
    secrets:
      - name: git_mirror_credentials
        secret: stx-app-oran-o2-github-secret3
        pass-to-parent: true

- secret:
    name: stx-app-oran-o2-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - JPJ15XfF3tgYX6+Z/OuEaxri7yG3ckVFhKIGtsae59B+fzFw8MAkyX/bFkq4ZgQibTgpl
          eRCApmvOLCHQXydkonwNULSsodeEvQ9JyI6Yp8kuwo6sNyHOWwUSp0zi5oMpSKT04f7D6
          0AgGj8NUDHCUqauPVDxNaqC3H3Do7ma95XajENmHoPK/uyXoh+1l6/jJRbqX9wVFl52i1
          fzKR195v/nm78Oo8K0LnyrXmZen/foL8jCLQwoU7c2lAtt8X39sEKphxSoTDwSu6HrtoT
          9tvup62HXwLMVJwbZITsXHaX2Lk5QQ69N2UCg/avAm1Rc1vHtg0gcgFUHehP7c+AiwDdY
          jFO/qL6wqjMLJN0QOrtDN3Jf45kOQyJ3xdOpsOdy5xNuyutSLqLm8teSBmgKNqI7ThvLy
          TqbISJQTBXWu88ANyKHOnHpSwK/N/xIK7jjdpc1kZAzbSl36lOJDRT3EOPsKmciSU2Nf5
          OC70MmIFwWu8ENgxLiTlzjZfvlGT8myvjLe0Z9GxR/et2IOFk5QHFqpFrcrETJwEhQ3Iu
          uAHuEzEzujZ2gUZVgYb+jeUBXBUowTFcIANn78N4d1a0cVD4MomLJCHh7YQvWHDIoLZBB
          rCrq3jcOrTd8naopqTj9J2aS+jcSHaINQCVQ648RQpIjkcMIJ02LQp4+oJsMJI=
        - cLVDnXRng8+AQKIFKFWHHindUyfdmxwBFGai6vlldSKAiErgSBXD/QZWANJoxbIEukoEK
          /BwpT6NBF7RTPTkkrW9LFTXr7zq/8m+izBxFEwdtTWajoCXcCq0rhjsSAo6myWjWMpiqO
          Aam9R2FN4j+mp2Cs6cEifABCUquDaSLzvMvLH5Cv7PRTxLZIZKxw5747FVlN50MgVg1BT
          IePfjDeViRkp2KWi6kRQp03LtYrRj8kh1DWSC4116Zw0JXeLHtfDHaDaFdJdEQkO0JxkU
          l1+e8paYJdiFqawwmguMOb8A3qJPeLSa57fPwnXOTqKTH4oxKW7raFfTaRa8IcgLFCOHD
          aNdM0dVj8WwLv5hdpOeIP+7F/hRa4wmc+oM32cecuSfTonIvY2GzyBPHv3I4uzgEx0u4j
          CHmXFl3TiXcm8Bbo5DnoVn+jT2CdiUFMVQ0F7KyTavxI9mP1jPeftwUICpqbz97nT4l4z
          JHqscsPzMKHJnlFRkms+agcr4nkf8J1Cz/eYN/Z1HkSaYsI4XJP3z3iqh4ThC2boGcLJw
          98m6gSUWmusHUMgG499Ql7t5irI7WEIv1tGjy1B6PtjsBfmhBy4q6lebFiWVAJNKC9YC6
          FBVJjMx1MPBjWc2swD1rScKrDfL6nYdvLBXQuEkPBMfY+/HfMFMsgll7XyoKl8=
        - M+9jC5LibpJvZ4FhqJ7wHYd96MZWfIPORICJDE4pIor4fWQ8tlFNByh23nqZx/WbT0dF1
          o13booBqVL8P93vwsxOoiAWK6I+GMowj3GjQvQviBB8fKr4RWuM2ToRdyySRRV4ee+y6i
          +qJaEb2he24GnGSpVt90VwWJE1fkGIb41aZn4z+2ZBVywUsxoGMCmekPeB4R27tlyfjwj
          Tce+/JisMl/wzZ1G+hZ0x6eOjZU+h6McaxgjzF+X2lsam7CdYGNWLxIIlbaii7L7GTN0a
          Rdk9heFEpblJw1KtlhPLiOpYB31lEdtwPGfSKIwikQx8j8HIJ7u4AxUVGwPWqwN7TBOP7
          pna2iFpt+z7PS4zNUmPynB5U53jksxXG5tyqKqNUQSQtP/o9rhrJrYmA1yaXLByRnR8tk
          3MUt6Q5ZMPcnosG66gBREmTIDOAyK8FlhrdBXKuaFID8UlTTK1nyHzD7Sbzl3iQBsEzF4
          rn5ZkoYSHNFs35siUCC/fyh4WsgLRcc6T8Edd3fpy4vNE+PxKYqvOCLWYho5cJm867yZx
          B/cdZPG5NVLNVLp2AzunjrYR6WZAJKIuV/2zJfiGA+OuhlmJwkNRtQizHTq9+dfrCeVNU
          OXiIjnBFtrvr1c3cY+t64yHSte2xYylIYQOHLI6db6AOmLzsW24LseSPKvxRzk=
        - Y2Q8yXjN0CgiUmavTLYaTvJfm+5Otl6qbsOzuv2yaPhn0y147QGR2O6kKtmm1Z4PgQySK
          AqG+yTjYAcsKqF4Kqfe3w0CvmxVYb3HRqXQPYAen781xwgZWT6bZVqL+GHfCt/nRIQwX2
          dl3oFlAqNv8J0XqfcrO8BcWqGLvedC/QtmON0GJrK7XWrTdgHpG72e0jwe2+jsZ14ykEV
          CHgv/+GiB1kDgJ53H6QkzFIag8VbFUCBG6pw0hx0UHX6rkdG/grYijL1DCE+0EsNJXw4r
          S94YBK9Mu823Z+dq/plp+x0ZXDI+SNa28hxam8tDE2VcBg9K3NymhN1AamUs9xcTZ+wQu
          YDMIgyRVc3fYBFa9dW2zzaUfSM20Ot3Qk3UJdQdESEMVQOZ8ohN5rigRa7vwBPuF42Mya
          lnTs7n1CkWSEyfxD0Eb+rIzDRTNG8Ue4D7zkhXVgUu73aFNM8aNlNhqeBoMQer9Cv5WH0
          FeacKo9v7SkqL4NS2aOWp6sigkBhXU4AKvcFgo/qBQ9BUnRGVmx06GRWL8/BUCgsoAJdT
          FIRQ3JM9tbZhQVm8upoHsROuX9b1pygB4mqZetP8tazb+epvqE6W/CQBsdopy6C9YAKY3
          ptlGwb2KyRFhMHmjM3FpdBY7DhfUYIDOf9KTvQCboEr0e2oGBe4lF4mmMzr6sM=
        - M70542q7oxjOqnSQYvW4PR5ZsG91mAq/92vf+Z1rSsNrSZPbHkGUsgdvYn/Tx23xPbyMq
          PNKCgWIWF98fgJu72bnJvaQbFTKxC9xP9Y3Z2opj3Hjc0Ewl2393qMbFXGdGJOsa+iQhr
          qiZ8AcM5xt/6vi6CJYsXzh8B0m+1drIRgFPi8S/DuEBzjVfUcqph6JAP62AsId913pgou
          J83bbRAG6MJy6Mn9tHCTc52iVuAMBwokpScTKrxGJqFbjKG7oWsR9A4t8DIYZoLO75u1e
          zayiL0/gO2H459EIyQWru19ZgKX60V2bOzacP00Qr8b0JAc3d8QIFovV2dSwJbTRQ6xjQ
          +FgXbBzcujQGcneHJialxCkEBxHz3cdeU8WOO/sIuTSKIB2R74I2tu7dIk/wKGAq5ZgRB
          AUeIaYpSI+P8KR03ADpIwTRf8IdTxVaqenOlNjMILUjUAhVzgyt0fUKFuctc8CBAhYPU2
          oXRuQoi7EvGTtxTSEbh2AYz8XgTOG7EvWKaEeT981xqTe40uS7/oaxoFfQ42nySJbkyMc
          lOJd/2NeYxympWs1kJqsHtH6wxGfmdUqviP4nd06mruLRe8zDRPQBr/nFW1CLn0cMW+Ki
          +3enpVAcnd7l4g67XeX096M2AtpKDQ64lWoKQ4TzAS0nZ4zpL3/FnbZCSgdXlA=
        - jp6LPvD+wKCbE1SzYZVetoetfw66x2Mcx0zYCdRHQ1OlOexgSqJ7d6/Tablirp154ltb9
          X5S7EwDXbpr6asSH2iscXEnUrKyZhLk/DNU6fjQzGJ6qhwF6V6vY1soZp7p5lg5Z2NqAo
          tt899ysi3eaGPHFn/taKFEt4d8ANAS4FqU1LL4o2E7JxOvWkcBhtvhlZJI7DBRnROCPBw
          V4B3hAolmRf+Nu5x4FQrQXSTpipJgLpk3PWWCaMkqK4imp6z6k4ti7aUdzXl10GhFHzKu
          3rUTMEea5jsyWHPi9IJ5/jYnEhrdX0rgwfvdDQ+9ie0d8mLzovUR0MRbxcNMYREvinejg
          S14SKnpiecpJ991x9d4lPMB7AkDrebc8u2QzisUS9MZBD6RAgzkmoWPDeCYE5UFC/ZdIp
          7n7MLMGHrCSRWWz+ZTRKdw3Zp6e1r+3WHKxbhsZrCeqylRnJJ0zQN0be752k0e0FTcnFj
          4CkCJcVjbMuinN/WA9VaCmBqQ70nonYvkunqRL8q/ZVPYlZeBFQB+Uw5dFLNKTJIeRX24
          2XcmUNteLP0RMTGENFqK5DXFzOqDr3x1z2fe1wvT6NE5AigJhibk3RM07waYoYF1ChgGx
          dh4Jjig+sxlU/IyV2EUzY9DfQKoBs9w8xPLbCgYhzJPQ1o6jjfymxYoVa2LGyo=
        - GmHmmKbwXw3ueH4JZNjSymIuNcSkn/YHfz9OkJRwiIUAqsm7br4jHXcVKR3ZRXdKI9LU4
          1mQKGZTr+q49IKfds8T98rMI14m9FY5BuC7z0UddjrnL2Q/W9Aru4mhS1s4v0Y49jbEty
          uY+/5bqvQFuSiq+yIW5R8UhYtQp4Eal6M4IEajttpziwwTmBYQ2TRYsW/uLC/bGbAvc4V
          bX7PORGWVDY2lIdkMLprKN1IboDkWZ33yfNS/OSmjBL0CJI+LiuUuj+Y+TwuRoPxjqcDz
          jfzmC+00xPSoJC9YSZkqMZfZancuQx1cKasoK7Q4gxVFF0tiD/qAIfLfyEzxgfl/CwLLO
          7+CgWpd93+poJRZG9bCAYli8Sox+wl3wGHZNWAlz05WgQRBG1qU61xy7w/bQ7oAmwdd5S
          obwSnWEm6O5n4j2yLx/bZAfbyaYB5pzBFh9Oxs+WUFTseirn7M+lIe2qrCLFQe4ZPFhlv
          sPst0yZz5kUN0o94JibEA6tqVPs1OifgpqYtlpdw8oN5tTwqzngwpMXmp6H3n2OdewkVz
          FfWIDFhKlkC4EQ+8z2ZhM5RT2LuxDT9Gv7ZmPKzCUrrWWr/gDGAN3N75NEwRU7RNbhlyy
          QeHyLUsa//KeXA6fARYLUp1m/nmHKTj//GBmHOCjeBsGJj7alyKlO8t2u1o1MM=

- job:
    name: k8sapp-oran-o2-tox-py313
    parent: tox
    description: |
      Run py313 unit tests for k8sapp-oran-o2 (Trixie)
    nodeset: debian-trixie-8GB
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: py313
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/trixie/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-pylint-trixie
    parent: tox
    description: |
      Run pylint test for k8sapp-oran-o2 (Trixie)
    nodeset: debian-trixie-8GB
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: pylint-trixie
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/trixie/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-flake8-trixie
    parent: tox
    description: |
      Run flake8 test for k8sapp-oran-o2 (Trixie)
    nodeset: debian-trixie-8GB
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: flake8-trixie
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/trixie/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-metadata-trixie
    parent: tox
    description: |
      Run metadata test for k8sapp-oran-o2 (Trixie)
    nodeset: debian-trixie-8GB
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata-trixie
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/trixie/upper-constraints.txt'

- job:
    name: k8sapp-oran-o2-tox-coverage-trixie
    parent: tox
    description: |
      Run coverage analysis for k8sapp-oran-o2 (Trixie)
    nodeset: debian-trixie-8GB
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: coverage-trixie
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/trixie/upper-constraints.txt'
    post-run: python3-k8sapp-oran-o2/k8sapp_oran_o2/k8sapp_oran_o2/tests/playbooks/upload-coverage-reports.yaml

- job:
    name: k8sapp-oran-o2-tox-bandit-trixie
    parent: tox
    description: |
      Run bandit security analysis for k8sapp-oran-o2 (Trixie)
    nodeset: debian-trixie-8GB
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oran-o2/*
    vars:
      tox_envlist: bandit-trixie
      tox_extra_args: -c python3-k8sapp-oran-o2/k8sapp_oran_o2/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/trixie/upper-constraints.txt'
    post-run: python3-k8sapp-oran-o2/k8sapp_oran_o2/k8sapp_oran_o2/tests/playbooks/upload-bandit-reports.yaml